#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# for adding multiple monitors and workspaces
bspc monitor HDMI-1 -d I II III IV V 
bspc monitor eDP-1 -d VI VII VIII IX X

bspc config border_width		2
bspc config window_gap			10
bspc config top_padding			50
bspc config bottom_padding		10
bspc config left_padding		10
bspc config right_padding		10
bspc config single_monocle		false
bspc config gapless_monocle     true
bspc config split_ratio         0.52
bspc config borderless_monocle  true

bspc config focus_follows_pointer		true

bspc config pointer_modifier	mod4
bspc config pointer_action1		move
bspc config pointer action2		resize_side
bspc config pointer_action3		resize_corner

# Colors
bspc config normal_border_color		"#504945"
bspc config active_border_color		"#8ec07c"
bspc config focused_border_color	"#98971a"
bspc config presel_feedback_color	"#a89984"

# Polybar config
killall -q polybar
polybar -c ~/.config/polybar/mycustom/config.ini HDMI-1 &
polybar -c ~/.config/polybar/mycustom/config.ini eDP-1 &

# Multi-monitor setup config
~/.screenlayout/setup2.sh &

# Picom launch
picom --experimental-backends &

# Setup wallpaper with feh
feh --bg-fill ~/Pictures/wallpaper4.jpg &

# Autolock with xautolock and i3lock
xautolock -time 10 -notify 30 -notifier 'notify-send "Lock" "Your pc will lock in 30s"' -locker 'i3lock-fancy-multimonitor -n -b=0x16' &


# Application specific rules
bspc rule -a feh state=floating
